### ISSUE TITLE
the server doesn’t use the jekyll 404 template?

### ISSUE THREAD

**Issue by jasikpark** [QuietMisdreavus/fosspride.org#2]
![image](https://user-images.githubusercontent.com/10626596/89115862-c96d1f00-d452-11ea-8606-0e0faf6a89db.png)

for https://fosspride.org/pride-images/git-pride

**Comment by QuietMisdreavus** [comment]
This was because this site is pushed to nearlyfreespeech.net, which needs a `.htaccess` file to use custom 404 pages. I've got the fix pushed now. Nice catch, thanks for the report!

**Comment by jasikpark** [comment]
great!
